CLASS_ROBOT = 0
CLASS_BALL = 1
CLASS_FIELD = 2

CONF_THRESHOLD = 0.25
MAX_ROBOTS = 4
MAX_BALL_AGE = 10
MAX_ROBOT_AGE = 12
NMS_IOU_BALL = 0.0
FIELD_CACHE_EVERY = 30

ROBOT_TEMPORAL_GATE_PX = 120.0
ROBOT_TEMPORAL_IOU_GATE = 0.08
ROBOT_TEMPORAL_MIN_AREA_RATIO = 0.45
ROBOT_TEMPORAL_MAX_AREA_RATIO = 2.4
ROBOT_DUPLICATE_CENTER_GATE_PX = 38.0
ROBOT_DUPLICATE_IOU_GATE = 0.32
ROBOT_ROI_SIZE_PX = 320
ROBOT_ROI_EXPANDED_SIZE_PX = 480
ROBOT_ROI_INFER_SIZE_PX = 640
ROBOT_FALLBACK_CONFIDENCE = 0.42
ROBOT_FALLBACK_MIN_BOX_AREA = 700
ROBOT_FALLBACK_MAX_BOX_AREA = 45000
ROBOT_FALLBACK_MIN_FILL_RATIO = 0.16
ROBOT_FALLBACK_MIN_CIRCULARITY = 0.10
ROBOT_FALLBACK_SPLIT_MIN_AREA = 9000
ROBOT_FALLBACK_SPLIT_MIN_SEPARATION_PX = 45.0

BALL_ROI_SIZE_PX = 256
BALL_ROI_INFER_SIZE_PX = 640
BALL_SEARCH_RADIUS_PX = 80.0
BALL_SEARCH_GROWTH_PX = 15.0
BALL_MAX_SEARCH_RADIUS_PX = 200.0
BALL_RECOVERY_AFTER_FRAMES = MAX_BALL_AGE + 1
BALL_GLOBAL_REACQUIRE_AFTER_FRAMES = 45
BALL_GLOBAL_REACQUIRE_EVERY_FRAMES = 5
BALL_GLOBAL_REACQUIRE_MAX_DISTANCE_PX = 260.0
BALL_GLOBAL_REACQUIRE_MIN_ORANGE_RATIO = 0.20
BALL_GLOBAL_REACQUIRE_MIN_CIRCULARITY = 0.68
BALL_GLOBAL_REACQUIRE_MIN_FIELD_RATIO = 0.45
BALL_CONFIDENCE_WEIGHT = 90.0
BALL_ORANGE_WEIGHT = 70.0
BALL_DISTANCE_WEIGHT = 0.85
BALL_RECENT_REJECT_MARGIN_PX = 30.0

TEXT_PROMPTS = [
    "small wheeled soccer robot on green field",
    "small bright orange circular ball on green floor, vivid saturated orange dot, overhead view",
    "flat green soccer field surface",
]

ROI_BALL_PROMPTS = [
    "bright orange ball",
    "small orange circular ball",
    "orange soccer ball",
    "vivid orange dot",
]

ROI_ROBOT_PROMPTS = [
    "wheeled soccer robot",
    "small soccer robot",
    "robot on green soccer field",
    "round wheeled robot",
]
